# Generated by Django 4.0.4 on 2022-05-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Flow', '0002_alter_cardata_car_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_detils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=50, null=True)),
                ('Product_Price', models.CharField(max_length=50, null=True)),
                ('Product_Id', models.CharField(max_length=50, null=True)),
                ('Product_Image', models.ImageField(upload_to='imgs')),
            ],
        ),
        migrations.AlterField(
            model_name='cardata',
            name='Car_Desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='Car_Id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='Car_Image',
            field=models.ImageField(upload_to='imgs'),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='Car_Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='Car_Price',
            field=models.IntegerField(null=True),
        ),
    ]
