# Generated by Django 4.0.4 on 2022-05-24 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Flow', '0004_product_detils_product_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product_detils',
            new_name='product_detil',
        ),
    ]
