# Generated by Django 4.0.4 on 2022-06-01 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Flow', '0005_rename_product_detils_product_detil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product_detil',
        ),
    ]
