# Generated by Django 4.1.5 on 2023-01-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App_Flow", "0009_moviedata_delete_cardata_delete_fruitdata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="moviedata", old_name="movie_Price", new_name="movie_rating",
        ),
    ]
